name: Linting with Super Linter

on:
  push:
    branches:
      - main

permissions:
  statuses: write  # Allow write access to status checks
  contents: read   # Read access to contents for the linter to analyze files

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUN_LINTERS: "true"  # Run all linters
          LINTER_RULES: "false"  # Disable specific linter rules to simplify debugging
        continue-on-error: true  # Continue even if linting errors are found (optional)
